/* Base de Données 2
 * Gestion d'un cinéma
 *
 * Alexis Giraudet 
 * François Hallereau 
 * Valery Morozov
 */

-- Supression des rôles

DROP ROLE TAB_AFF_FILMS_EN_COURS;
DROP ROLE CAISSE_ENREG;
DROP ROLE TAB_AFF_SEANCES_A_VENIR;
DROP ROLE TAB_AFF_FILMS_A_LAFFICHE;
DROP ROLE TAB_AFF_TARIFS;

-- Création des rôles

CREATE ROLE TAB_AFF_FILMS_EN_COURS;
CREATE ROLE CAISSE_ENREG;
CREATE ROLE TAB_AFF_SEANCES_A_VENIR;
CREATE ROLE TAB_AFF_FILMS_A_LAFFICHE;
CREATE ROLE TAB_AFF_TARIFS;

-- Attribution des droits en fonction des rôles

GRANT SELECT ON SEANCE TO TAB_AFF_FILMS_EN_COURS;
GRANT SELECT ON FILM TO TAB_AFF_FILMS_EN_COURS;
GRANT SELECT ON SALLE TO TAB_AFF_FILMS_EN_COURS;
GRANT ALL ON ACHAT TO CAISSE_ENREG;
GRANT SELECT ON TARIF TO CAISSE_ENREG;
GRANT SELECT ON SEANCE TO CAISSE_ENREG;
GRANT SELECT ON SALLE TO CAISSE_ENREG;
GRANT SELECT ON SEANCE TO TAB_AFF_SEANCES_A_VENIR;
GRANT SELECT ON FILM TO TAB_AFF_SEANCES_A_VENIR;
GRANT SELECT ON FILM TO TAB_AFF_FILMS_A_LAFFICHE;
GRANT SELECT ON TARIF TO TAB_AFF_TARIFS;
